# ==============================================
# collector采集程序外部配置文件
# 修改本文件参数，不需要重新编译C程序
# 格式：key=value  #号代表注释
# ==============================================

# ----------------硬件GPIO(sysfs编号)----------------
GPIO_RUN_STATUS=1        #设备运行状态引脚，杜邦线短接GND代表设备运行
GPIO_CNT_PRODUCT=0       #E18‑D80NK红外产量检测引脚
BUZZER_GPIO=3            #蜂鸣器输出引脚

# ----------------业务逻辑参数----------------
TEMP_THRESHOLD=30        #温度报警阈值(℃)，大于等于该值本地蜂鸣器报警
ALARM_COOLDOWN=10        #报警冷却时间(秒)，防止蜂鸣器频繁鸣叫
RING_BUF_SIZE=16         #环形缓冲区最大存储条数
DEVICE_ID=1001           #采集设备编号，服务端区分不同采集板

# ----------------TCP服务端配置----------------
SERVER_IP=192.168.14.50#成员A中转服务端IP地址
SERVER_PORT=8888#服务端监听端口
